### ISSUE TITLE
Bring in resource terms and synonyms directly from web ontology urls

### ISSUE THREAD

**Issue by ivansg44** [Public-Health-Bioinformatics/LexMapr#30]
Rather than use a fixed collection of terms and synonyms in the resources folder, we should try to generate these files with up-to-date terms and synonyms directly from web ontology urls.

We can use this:
https://github.com/GenEpiO/geem/blob/master/scripts/ontofetch.py

**Comment by Public-Health-Bioinformatics** [comment]
it will be a size/performance issue whether a single cached resource file can fit all the particular ontologies into it, but I think it should be able to. It would be organized as a dictionary of dictionaries...

lookup.onto['GAZ']{key:value}
lookup.onto['GENEPIO']{key:value}
lookup.onto['DOID']{key:value}
etc.
Otherwise This data structure would have to be built by reading in individual ontologies according to desired ontologies **each time script was run**.

Given that lexmapr needs to be turned into a memory resident service, its an attractive design decision to have it load once with all available resources, and then gets called with (API) requests that normally select a subset of the ontologies.

**Comment by ivansg44** [comment]
[Done.](https://github.com/Public-Health-Bioinformatics/LexMapr/commit/7122a6029f45e3d72b98cdf2286ebb869b3e21ef)
